name: e-Shop Web Application

trigger:
  branches:
    include:
      - master
      - dev
      - test

pr:
  - master

resources:
  repositories:
  - repository: pipelinetemplates # The name used to reference this repository in the checkout step
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure_shared_components'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinetemplates
  parameters:
    projectName: 'eShop On Web'
    workingDirectory: 'eshoponweb'
    buildType: 'dotnet'
    dotnetCoreSDKVersion: '5.0.403'
    sonarProjectKey: 'eshop-web'
    infraTerraformFolder: 'infrastructure'
    dockerFilePath: 'src/Web/Dockerfile'
    dotnetProjectORSolution: 'src/Web/Web.csproj'

    # sonarProjectKey: 'spring-boot-application'
    # beforeJobSteps:
    #   - script: echo "FROM BEFORE BUILD STAGE"
    #     displayName: 'Pre build'
    # afterJobSteps:
    #   - script: echo "FROM AFTER BUILD STAGE"
    #     displayName: 'Post build'
