# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: Ubuntu-latest

steps:


- task: Docker@2
  inputs:
    containerRegistry: 'ACR_SVC_CONNECTION'
    repository: 'eshop/api'
    command: 'buildAndPush'
    Dockerfile: '**/src/PublicApi/Dockerfile'
    buildContext: '.'
    tags: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR_SVC_CONNECTION'
    repository: 'eshop/web'
    command: 'buildAndPush'
    Dockerfile: '**/src/Web/Dockerfile'
    buildContext: '.'
    tags: '$(Build.BuildId)'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AKSTerraformSPN'
    KeyVaultName: 'azureterraformtestvault'
    SecretsFilter: '*'
    RunAsPreJob: false
