name: e-Shop Web Application

trigger: none
  # branches:
  #   include:
  #   - master
  #   - refs/pull/*

resources:
  repositories:
  - repository: pipelinetemplates # The name used to reference this repository in the checkout step
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure_shared_components'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinetemplates
  parameters:
    agentPool: 'windows-2019'
    checkOutSteps:
      - checkout: self
      - checkout: pipelinetemplates
    projectName: 'Spring Boot App Gradle'
    workingDirectory: 'eshoponweb'
    buildType: 'dotnet'
    dotnetCoreSDKVersion: '5.0.403'
    sonarProjectKey: 'eshop-web'
    infraTerraformFolder: 'infrastructure'
    dockerOrgName: 'vijayace'
    buildDockerImage: false
    dotnetProjectORSolution: '/eShopOnWeb.sln'

    # sonarProjectKey: 'spring-boot-application'
    # beforeJobSteps:
    #   - script: echo "FROM BEFORE BUILD STAGE"
    #     displayName: 'Pre build'
    # afterJobSteps:
    #   - script: echo "FROM AFTER BUILD STAGE"
    #     displayName: 'Post build'
