name: e-Shop Web Public Api

trigger:
  branches:
    include:
      - master
      - dev
      - test

pr:
  - master

resources:
  repositories:
  - repository: pipelinelibrary # The name used to reference this repository in the checkout step. This name must be set to pipelinelibrary
    type: github
    endpoint: 'vijaykumar-r'
    name: 'vijaykumar-r/azure-pipeline-library'
    ref: refs/heads/master

extends:
  template: pipeline_templates/pipeline_template.yml@pipelinelibrary
  parameters:
    projectName: 'eShop Public Api'
    workingDirectory: 'eshoponweb'
    buildType: 'dotnet'
    dotnetCoreSDKVersion: '5.0.403'
    sonarProjectKey: 'eshop-web'
    infraTerraformFolder: 'infrastructure'
    dockerFilePath: 'src/PublicApi/Dockerfile'
    dotnetProjectORSolution: 'src/PublicApi/PublicApi.csproj'

    # sonarProjectKey: 'spring-boot-application'
    # beforeJobSteps:
    #   - script: echo "FROM BEFORE BUILD STAGE"
    #     displayName: 'Pre build'
    # afterJobSteps:
    #   - script: echo "FROM AFTER BUILD STAGE"
    #     displayName: 'Post build'
